version: '3.8'
services:
  pg-database:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      retries: 5
    networks:
      - pg-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg-database
    networks:
      - pg-network
  
networks:
  default:
    name: pg-network

